/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Vazirmatn', 'Segoe UI', 'Tahoma', 'sans-serif'],
        mono: ['ui-monospace', 'SFMono-Regular', 'Menlo', 'monospace'],
      },
      colors: {
        primary: {
          50: 'var(--c-primary-50)',
          100: 'var(--c-primary-100)',
          200: 'var(--c-primary-200)',
          300: 'var(--c-primary-300)',
          500: 'var(--c-primary-500)',
          600: 'var(--c-primary-600)',
          700: 'var(--c-primary-700)',
          800: 'var(--c-primary-800)',
          900: 'var(--c-primary-900)',
        },
        surface: 'var(--c-surface)',
        'surface-2': 'var(--c-surface-2)',
        'surface-3': 'var(--c-surface-3)',
        bg: 'var(--c-bg)',
        border: 'var(--c-border)',
        'border-strong': 'var(--c-border-strong)',
        text: 'var(--c-text)',
        muted: 'var(--c-text-muted)',
        faint: 'var(--c-text-faint)',
        success: 'var(--c-success)',
        'success-bg': 'var(--c-success-bg)',
        warning: 'var(--c-warning)',
        'warning-bg': 'var(--c-warning-bg)',
        danger: 'var(--c-danger)',
        'danger-bg': 'var(--c-danger-bg)',
        info: 'var(--c-info)',
        'info-bg': 'var(--c-info-bg)',
        accent: 'var(--c-accent)',
        'accent-bg': 'var(--c-accent-bg)',
        'accent-border': 'var(--c-accent-border)',
        nav: 'var(--c-nav)',
        'nav-2': 'var(--c-nav-2)',
        'nav-text': 'var(--c-nav-text)',
        'nav-muted': 'var(--c-nav-muted)',
        neutralx: 'var(--c-neutral)',
        'neutralx-bg': 'var(--c-neutral-bg)',
      },
      boxShadow: {
        card: '0 1px 2px rgba(16, 24, 40, 0.05)',
        raised: '0 4px 12px rgba(16, 24, 40, 0.08)',
        overlay: '0 16px 48px rgba(16, 24, 40, 0.18)',
      },
      borderRadius: { xl: '10px', '2xl': '14px' },
      fontSize: {
        '2xs': ['0.6875rem', { lineHeight: '1rem' }],
      },
      keyframes: {
        fadeIn: { '0%': { opacity: '0' }, '100%': { opacity: '1' } },
        slideInEnd: { '0%': { transform: 'translateX(-16px)', opacity: '0' }, '100%': { transform: 'translateX(0)', opacity: '1' } },
        riseIn: { '0%': { transform: 'translateY(6px)', opacity: '0' }, '100%': { transform: 'translateY(0)', opacity: '1' } },
        shimmer: { '100%': { transform: 'translateX(-100%)' } },
      },
      animation: {
        fadeIn: 'fadeIn .18s ease-out',
        slideInEnd: 'slideInEnd .22s cubic-bezier(.22,1,.36,1)',
        riseIn: 'riseIn .2s ease-out',
      },
    },
  },
  plugins: [],
};
