import {
  Rule,
  RuleVersion,
  RulePack,
  RulePackVersion,
  RulePrecedence,
  RuleRequest,
  RuleAudit,
  RuleRequirement,
} from './types.ts';
import { computeRuleContentHash, computeSourceHash } from './ruleEngine.ts';

/* ============================================================
   SEED RULES & SEED RULE VERSIONS
   (Structured Urban Planning Rules with provenance & typed AST)
   ============================================================ */

export const SEED_RULES: Rule[] = [
  {
    code: 'RL-DENSITY-01',
    title: 'سقف تراکم ساختمانی مجاز در پهنه مسکونی عام (R122)',
    category: 'DENSITY',
    jurisdiction: 'طرح تفصیلی شهر تهران — منطقه ۶',
    current_published_version: 4,
    latest_version: 4,
    owner: 'مهندس لیلا اکبری (متولی قواعد و ضوابط)',
    created_at: '۱۴۰۴/۰۸/۱۰',
    updated_at: '۱۴۰۵/۰۲/۱۸',
    rule_pack_ids: ['PACK-TEH-2026'],
    dependent_study_ids: ['ST-1405-014', 'ST-1405-021'],
  },
  {
    code: 'RL-COVERAGE-01',
    title: 'حداکثر سطح اشغال مجاز ابنیه مسکونی',
    category: 'SITE_COVERAGE',
    jurisdiction: 'طرح تفصیلی شهر تهران — منطقه ۶',
    current_published_version: 4,
    latest_version: 4,
    owner: 'مهندس لیلا اکبری (متولی قواعد و ضوابط)',
    created_at: '۱۴۰۴/۰۸/۱۰',
    updated_at: '۱۴۰۵/۰۲/۱۸',
    rule_pack_ids: ['PACK-TEH-2026'],
    dependent_study_ids: ['ST-1405-014'],
  },
  {
    code: 'RL-STOREYS-01',
    title: 'حداکثر تعداد طبقات مجاز بر اساس عرض گذر و مساحت قطعه',
    category: 'STOREYS',
    jurisdiction: 'طرح تفصیلی شهر تهران — پهنه سکونت',
    current_published_version: 4,
    latest_version: 4,
    owner: 'مهندس لیلا اکبری (متولی قواعد و ضوابط)',
    created_at: '۱۴۰۴/۰۹/۰۱',
    updated_at: '۱۴۰۵/۰۲/۱۸',
    rule_pack_ids: ['PACK-TEH-2026'],
    dependent_study_ids: ['ST-1405-014'],
  },
  {
    code: 'RL-PARKING-01',
    title: 'الزام تأمین قطعی پارکینگ بر حسب کاربری و تعداد واحد',
    category: 'PARKING',
    jurisdiction: 'طرح تفصیلی شهر تهران — کلیه مناطق',
    current_published_version: 4,
    latest_version: 4,
    owner: 'مهندس لیلا اکبری (متولی قواعد و ضوابط)',
    created_at: '۱۴۰۴/۰۹/۱۵',
    updated_at: '۱۴۰۵/۰۲/۱۸',
    rule_pack_ids: ['PACK-TEH-2026'],
    dependent_study_ids: ['ST-1405-014', 'ST-1405-021'],
  },
  {
    code: 'RL-SETBACK-01',
    title: 'رعایت بر اصلاحی و حریم عقب‌نشینی معابر شریانی',
    category: 'SETBACK',
    jurisdiction: 'طرح تفصیلی شهر تهران — محورهای اصلی',
    current_published_version: 4,
    latest_version: 4,
    owner: 'مهندس لیلا اکبری (متولی قواعد و ضوابط)',
    created_at: '۱۴۰۴/۱۰/۰۲',
    updated_at: '۱۴۰۵/۰۲/۱۸',
    rule_pack_ids: ['PACK-TEH-2026'],
    dependent_study_ids: ['ST-1405-014'],
  },
  {
    code: 'RL-HEIGHT-01',
    title: 'سقف ارتفاع مجاز ابنیه در مجاورت خطوط انتقال نیرو و معابر باریک',
    category: 'HEIGHT',
    jurisdiction: 'حریم خطوط انتقال نیرو و آیین‌نامه ایمنی شهر تهران',
    current_published_version: 2,
    latest_version: 2,
    owner: 'مهندس لیلا اکبری (متولی قواعد و ضوابط)',
    created_at: '۱۴۰۵/۰۱/۱۵',
    updated_at: '۱۴۰۵/۰۳/۱۰',
    rule_pack_ids: ['PACK-TEH-2026'],
    dependent_study_ids: ['ST-1405-005'],
  },
];

/* Initial Rule Versions */
export const SEED_RULE_VERSIONS: RuleVersion[] = [
  // 1. RL-DENSITY-01 v4 (PUBLISHED)
  {
    version_id: 'RL-DENSITY-01-v4',
    rule_code: 'RL-DENSITY-01',
    version_number: 4,
    title: 'سقف تراکم ساختمانی مجاز در پهنه مسکونی عام (R122)',
    description: 'تراکم ساختمانی مجاز در پهنه مسکونی عام حداکثر ۳۰۰٪ مساحت عرصه مشروط به رعایت نصاب تفکیک و مساحت قطعه.',
    category: 'DENSITY',
    jurisdiction: 'طرح تفصیلی شهر تهران — منطقه ۶',
    source: {
      document: 'ضوابط و مقررات طرح تفصیلی یکپارچه شهر تهران',
      version: 'نسخه مصوب کمیسیون ماده پنج — ۱۳۹۱',
      issuer: 'شورای‌عالی شهرسازی و معماری ایران / کمیسیون ماده ۵',
      document_date: '۱۳۹۱/۰۲/۱۵',
      page: 28,
      clause: 'بند ۴.۲ — جدول شماره ۲ پهنه‌بندی سکونت',
      effective_from: '۱۳۹۱/۰۳/۰۱',
      effective_to: null,
      source_uri: 'https://shahrsazi.tehran.ir/regulations/detailed-plan-clause-4-2',
      evidence: 'سند فیزیکی ابلاغی به شهرداری منطقه ۶ تهران، دبیرخانه ماده ۵',
      verification_status: 'VERIFIED',
    },
    inputs: [
      {
        name: 'zone_code',
        label: 'کد پهنه طرح تفصیلی',
        data_type: 'string',
        required: true,
        description: 'کد پهنه‌بندی مصوب (مانند R122)',
        allowed_values: ['R122', 'R121', 'R251', 'M111'],
      },
      {
        name: 'parcel_area',
        label: 'مساحت قطعه (عرصه)',
        data_type: 'number',
        unit: 'm2',
        required: true,
        description: 'مساحت عرصه پلاک بر حسب متر مربع',
      },
      {
        name: 'proposed_density_percent',
        label: 'تراکم پیشنهادی طرح',
        data_type: 'number',
        unit: 'percent',
        required: true,
        description: 'درصد تراکم ساختمانی پیشنهادی سناریو',
      },
    ],
    applicability_ast: {
      type: 'and',
      data_type: 'boolean',
      children: [
        {
          type: 'in',
          data_type: 'boolean',
          children: [
            { type: 'input_reference', data_type: 'string', input_name: 'zone_code' },
            { type: 'literal', data_type: 'set', value: ['R122', 'R121'] },
          ],
        },
        {
          type: 'greater_than_or_equal',
          data_type: 'boolean',
          children: [
            { type: 'input_reference', data_type: 'number', input_name: 'parcel_area' },
            { type: 'literal', data_type: 'number', value: 150 },
          ],
        },
      ],
    },
    assertion_ast: {
      type: 'less_than_or_equal',
      data_type: 'boolean',
      children: [
        { type: 'input_reference', data_type: 'number', input_name: 'proposed_density_percent' },
        { type: 'literal', data_type: 'number', value: 300 },
      ],
    },
    human_readable: 'اگر پهنه عضو [R122، R121] و مساحت قطعه ≥ ۱۵۰ متر مربع باشد، آنگاه درصد تراکم پیشنهادی ≤ ۳۰۰٪.',
    severity: 'BLOCKING',
    interpretation_notes: 'در صورت احراز تجمیع با قطعه مجاور، تا سقف ۲۰٪ تشویقی مشروط به تأیید کمیسیون معماری منطقه امکان‌پذیر است.',
    exceptions: [],
    precedences: [],
    test_cases: [
      {
        id: 'TC-DENS-01',
        name: 'حالت استاندارد مطابق ضابطه (تراکم ۲۵۰٪)',
        test_type: 'HAPPY_PATH',
        inputs: { zone_code: 'R122', parcel_area: 250, proposed_density_percent: 250 },
        expected_applicability: 'applicable',
        expected_outcome: 'pass',
      },
      {
        id: 'TC-DENS-02',
        name: 'مرز حداکثری تراکم مجاز (۳۰۰٪)',
        test_type: 'BOUNDARY',
        inputs: { zone_code: 'R122', parcel_area: 200, proposed_density_percent: 300 },
        expected_applicability: 'applicable',
        expected_outcome: 'pass',
      },
      {
        id: 'TC-DENS-03',
        name: 'تراکم بیش از حد مجاز (۳۲۰٪)',
        test_type: 'UPPER_BOUNDARY',
        inputs: { zone_code: 'R122', parcel_area: 200, proposed_density_percent: 320 },
        expected_applicability: 'applicable',
        expected_outcome: 'fail',
      },
      {
        id: 'TC-DENS-04',
        name: 'ورودی مفقود (مساحت قطعه خالی)',
        test_type: 'NULL_INPUT',
        inputs: { zone_code: 'R122', parcel_area: null, proposed_density_percent: 250 },
        expected_applicability: 'unknown',
        expected_outcome: 'unknown',
      },
      {
        id: 'TC-DENS-05',
        name: 'عدم شمول به دلیل پهنه غیرمسکونی (M111)',
        test_type: 'NOT_APPLICABLE',
        inputs: { zone_code: 'M111', parcel_area: 300, proposed_density_percent: 400 },
        expected_applicability: 'not_applicable',
        expected_outcome: 'not_applicable',
      },
    ],
    test_runs: [
      {
        test_case_id: 'TC-DENS-01',
        run_at: '۱۴۰۵/۰۲/۱۸',
        status: 'PASSED',
        actual_applicability: 'applicable',
        actual_outcome: 'pass',
      },
      {
        test_case_id: 'TC-DENS-02',
        run_at: '۱۴۰۵/۰۲/۱۸',
        status: 'PASSED',
        actual_applicability: 'applicable',
        actual_outcome: 'pass',
      },
      {
        test_case_id: 'TC-DENS-03',
        run_at: '۱۴۰۵/۰۲/۱۸',
        status: 'PASSED',
        actual_applicability: 'applicable',
        actual_outcome: 'fail',
      },
      {
        test_case_id: 'TC-DENS-04',
        run_at: '۱۴۰۵/۰۲/۱۸',
        status: 'PASSED',
        actual_applicability: 'unknown',
        actual_outcome: 'unknown',
      },
      {
        test_case_id: 'TC-DENS-05',
        run_at: '۱۴۰۵/۰۲/۱۸',
        status: 'PASSED',
        actual_applicability: 'not_applicable',
        actual_outcome: 'not_applicable',
      },
    ],
    status: 'PUBLISHED',
    content_hash: '',
    source_hash: '',
    approval_hash: 'appr-hash-dens-01-v4',
    approved_by: 'دکتر محمدرضا سلطانی (رئیس کمیسیون تخصصی شهرسازی)',
    approved_at: '۱۴۰۵/۰۲/۱۸',
    created_at: '۱۴۰۵/۰۲/۱۰',
    created_by: 'مهندس لیلا اکبری',
    effective_from: '۱۳۹۱/۰۳/۰۱',
    effective_to: null,
    is_synthetic: false,
  },

  // 2. RL-COVERAGE-01 v4 (PUBLISHED)
  {
    version_id: 'RL-COVERAGE-01-v4',
    rule_code: 'RL-COVERAGE-01',
    version_number: 4,
    title: 'حداکثر سطح اشغال مجاز ابنیه مسکونی',
    description: 'سطح اشغال مجاز در طبقات همکف و اول حداکثر ۶۰٪ مساحت عرصه پس از رعایت بر اصلاحی می‌باشد.',
    category: 'SITE_COVERAGE',
    jurisdiction: 'طرح تفصیلی شهر تهران — منطقه ۶',
    source: {
      document: 'دستورالعمل نظارت بر ساخت و ساز و ضوابط کالبدی شهرداری تهران',
      version: 'مصوب شورای اسلامی شهر تهران — ۱۳۹۸',
      issuer: 'شورای اسلامی شهر تهران',
      document_date: '۱۳۹۸/۰۶/۲۰',
      page: 14,
      clause: 'ماده ۵ — سطح اشغال مجاز در قطعات مسکونی',
      effective_from: '۱۳۹۸/۰۷/۰۱',
      effective_to: null,
      source_uri: 'https://shora.tehran.ir/acts/coverage-guideline-clause-5',
      evidence: 'روزنامه رسمی شماره ۲۱۷۰۴، ابلاغیه معاونت شهرسازی شهرداری تهران',
      verification_status: 'VERIFIED',
    },
    inputs: [
      {
        name: 'zone_code',
        label: 'کد پهنه',
        data_type: 'string',
        required: true,
      },
      {
        name: 'proposed_coverage_percent',
        label: 'سطح اشغال پیشنهادی سناریو',
        data_type: 'number',
        unit: 'percent',
        required: true,
      },
    ],
    applicability_ast: {
      type: 'in',
      data_type: 'boolean',
      children: [
        { type: 'input_reference', data_type: 'string', input_name: 'zone_code' },
        { type: 'literal', data_type: 'set', value: ['R122', 'R121', 'M111'] },
      ],
    },
    assertion_ast: {
      type: 'less_than_or_equal',
      data_type: 'boolean',
      children: [
        { type: 'input_reference', data_type: 'number', input_name: 'proposed_coverage_percent' },
        { type: 'literal', data_type: 'number', value: 60 },
      ],
    },
    human_readable: 'اگر پهنه عضو [R122، R121، M111] باشد، سطح اشغال پیشنهادی ≤ ۶۰٪.',
    severity: 'BLOCKING',
    exceptions: [],
    precedences: [],
    test_cases: [
      {
        id: 'TC-COV-01',
        name: 'سطح اشغال ۵۵٪ (منطبق)',
        test_type: 'HAPPY_PATH',
        inputs: { zone_code: 'R122', proposed_coverage_percent: 55 },
        expected_applicability: 'applicable',
        expected_outcome: 'pass',
      },
      {
        id: 'TC-COV-02',
        name: 'سطح اشغال ۶۵٪ (بیش از حد مجاز)',
        test_type: 'UPPER_BOUNDARY',
        inputs: { zone_code: 'R122', proposed_coverage_percent: 65 },
        expected_applicability: 'applicable',
        expected_outcome: 'fail',
      },
    ],
    test_runs: [],
    status: 'PUBLISHED',
    content_hash: '',
    source_hash: '',
    approval_hash: 'appr-hash-cov-01-v4',
    approved_by: 'دکتر محمدرضا سلطانی',
    approved_at: '۱۴۰۵/۰۲/۱۸',
    created_at: '۱۴۰۵/۰۲/۱۰',
    created_by: 'مهندس لیلا اکبری',
    effective_from: '۱۳۹۸/۰۷/۰۱',
    effective_to: null,
    is_synthetic: false,
  },

  // 3. RL-STOREYS-01 v4 (PUBLISHED)
  {
    version_id: 'RL-STOREYS-01-v4',
    rule_code: 'RL-STOREYS-01',
    version_number: 4,
    title: 'حداکثر تعداد طبقات مجاز بر اساس عرض گذر و مساحت قطعه',
    description: 'در پهنه R122 قطعات دارای مساحت بالای ۲۵۰ متر مربع و گذر حداقل ۱۲ متر، حداکثر ۵ طبقه مسکونی روی پیلوت مجاز است.',
    category: 'STOREYS',
    jurisdiction: 'طرح تفصیلی شهر تهران — پهنه سکونت',
    source: {
      document: 'ضوابط کالبدی طرح تفصیلی منطقه ۶ تهران',
      version: 'بازنگری سال ۱۳۹۹',
      issuer: 'کمیسیون ماده ۵ شهر تهران',
      document_date: '۱۳۹۹/۰۴/۱۸',
      page: 19,
      clause: 'بند ۳.۱ — جدول ارتفاع و طبقات پهنه R',
      effective_from: '۱۳۹۹/۰۵/۰۱',
      effective_to: null,
      source_uri: 'https://commission5.tehran.ir/approvals/r122-storeys-clause-3-1',
      evidence: 'مصوبه شماره ۵۸۴ کمیسیون ماده پنج شهر تهران',
      verification_status: 'VERIFIED',
    },
    inputs: [
      {
        name: 'zone_code',
        label: 'کد پهنه',
        data_type: 'string',
        required: true,
      },
      {
        name: 'proposed_floor_count',
        label: 'تعداد طبقات پیشنهادی',
        data_type: 'integer',
        unit: 'storey',
        required: true,
      },
    ],
    applicability_ast: {
      type: 'equals',
      data_type: 'boolean',
      children: [
        { type: 'input_reference', data_type: 'string', input_name: 'zone_code' },
        { type: 'literal', data_type: 'string', value: 'R122' },
      ],
    },
    assertion_ast: {
      type: 'less_than_or_equal',
      data_type: 'boolean',
      children: [
        { type: 'input_reference', data_type: 'integer', input_name: 'proposed_floor_count' },
        { type: 'literal', data_type: 'integer', value: 5 },
      ],
    },
    human_readable: 'اگر پهنه = R122 باشد، تعداد طبقات پیشنهادی ≤ ۵ طبقه.',
    severity: 'BLOCKING',
    exceptions: [],
    precedences: [],
    test_cases: [
      {
        id: 'TC-STOR-01',
        name: '۴ طبقه (مجاز)',
        test_type: 'HAPPY_PATH',
        inputs: { zone_code: 'R122', proposed_floor_count: 4 },
        expected_applicability: 'applicable',
        expected_outcome: 'pass',
      },
      {
        id: 'TC-STOR-02',
        name: '۵ طبقه (مرز مجاز)',
        test_type: 'BOUNDARY',
        inputs: { zone_code: 'R122', proposed_floor_count: 5 },
        expected_applicability: 'applicable',
        expected_outcome: 'pass',
      },
      {
        id: 'TC-STOR-03',
        name: '۶ طبقه (بیش از سقف مجاز)',
        test_type: 'UPPER_BOUNDARY',
        inputs: { zone_code: 'R122', proposed_floor_count: 6 },
        expected_applicability: 'applicable',
        expected_outcome: 'fail',
      },
    ],
    test_runs: [],
    status: 'PUBLISHED',
    content_hash: '',
    source_hash: '',
    approval_hash: 'appr-hash-stor-01-v4',
    approved_by: 'دکتر محمدرضا سلطانی',
    approved_at: '۱۴۰۵/۰۲/۱۸',
    created_at: '۱۴۰۵/۰۲/۱۰',
    created_by: 'مهندس لیلا اکبری',
    effective_from: '۱۳۹۹/۰۵/۰۱',
    effective_to: null,
    is_synthetic: false,
  },

  // 4. RL-PARKING-01 v4 (PUBLISHED)
  {
    version_id: 'RL-PARKING-01-v4',
    rule_code: 'RL-PARKING-01',
    version_number: 4,
    title: 'الزام تأمین قطعی پارکینگ بر حسب کاربری و تعداد واحد',
    description: 'به ازای هر واحد مسکونی در پهنه مرکزی و ایستگاهی، تأمین حداقل ۱ واحد پارکینگ قطعی در محل پلاک یا پارکینگ تجمیعی شعاع ۲۵۰ متری الزامی است.',
    category: 'PARKING',
    jurisdiction: 'طرح تفصیلی شهر تهران — کلیه مناطق',
    source: {
      document: 'بند ۳ مصوبه ۵۲۸ کمیسیون ماده پنج شهر تهران پیرامون ضوابط پارکینگ',
      version: 'مصوب ۱۳۹۳/۱۱/۰۴',
      issuer: 'کمیسیون ماده ۵ شهر تهران',
      document_date: '۱۳۹۳/۱۱/۰۴',
      page: 8,
      clause: 'بند ۳ — کسری پارکینگ و پارکینگ‌های تجمیعی محله‌ای',
      effective_from: '۱۳۹۳/۱۲/۰۱',
      effective_to: null,
      source_uri: 'https://commission5.tehran.ir/approvals/parking-resolution-528',
      evidence: 'ابلاغیه رسمی شماره ۹۳/۱۰۴۸۲ دبیرخانه کمیسیون ماده ۵',
      verification_status: 'VERIFIED',
    },
    inputs: [
      {
        name: 'land_use',
        label: 'کاربری اصلی بنا',
        data_type: 'string',
        required: true,
        allowed_values: ['residential', 'commercial', 'administrative'],
      },
      {
        name: 'residential_units_count',
        label: 'تعداد واحدهای مسکونی',
        data_type: 'integer',
        unit: 'count',
        required: true,
      },
      {
        name: 'provided_parking_spaces',
        label: 'تعداد پارکینگ تأمین‌شده',
        data_type: 'integer',
        unit: 'count',
        required: true,
      },
    ],
    applicability_ast: {
      type: 'equals',
      data_type: 'boolean',
      children: [
        { type: 'input_reference', data_type: 'string', input_name: 'land_use' },
        { type: 'literal', data_type: 'string', value: 'residential' },
      ],
    },
    assertion_ast: {
      type: 'greater_than_or_equal',
      data_type: 'boolean',
      children: [
        { type: 'input_reference', data_type: 'integer', input_name: 'provided_parking_spaces' },
        { type: 'input_reference', data_type: 'integer', input_name: 'residential_units_count' },
      ],
    },
    human_readable: 'اگر کاربری = مسکونی باشد، تعداد پارکینگ تأمین‌شده ≥ تعداد واحدهای مسکونی.',
    severity: 'BLOCKING',
    exceptions: [],
    precedences: [],
    test_cases: [
      {
        id: 'TC-PARK-01',
        name: 'تأمین مساوی پارکینگ (۱۰ واحد مسکونی، ۱۰ پارکینگ)',
        test_type: 'BOUNDARY',
        inputs: { land_use: 'residential', residential_units_count: 10, provided_parking_spaces: 10 },
        expected_applicability: 'applicable',
        expected_outcome: 'pass',
      },
      {
        id: 'TC-PARK-02',
        name: 'کسری پارکینگ (۱۰ واحد مسکونی، ۸ پارکینگ)',
        test_type: 'LOWER_BOUNDARY',
        inputs: { land_use: 'residential', residential_units_count: 10, provided_parking_spaces: 8 },
        expected_applicability: 'applicable',
        expected_outcome: 'fail',
      },
    ],
    test_runs: [],
    status: 'PUBLISHED',
    content_hash: '',
    source_hash: '',
    approval_hash: 'appr-hash-park-01-v4',
    approved_by: 'دکتر محمدرضا سلطانی',
    approved_at: '۱۴۰۵/۰۲/۱۸',
    created_at: '۱۴۰۵/۰۲/۱۰',
    created_by: 'مهندس لیلا اکبری',
    effective_from: '۱۳۹۳/۱۲/۰۱',
    effective_to: null,
    is_synthetic: false,
  },

  // 5. RL-SETBACK-01 v4 (PUBLISHED)
  {
    version_id: 'RL-SETBACK-01-v4',
    rule_code: 'RL-SETBACK-01',
    version_number: 4,
    title: 'رعایت بر اصلاحی و حریم عقب‌نشینی معابر شریانی',
    description: 'در محورهای شریانی اصلی با عرض گذر ۲۰ متر و بیشتر، رعایت حداقل ۳.۵ متر عقب‌نشینی از محور گذر الزامی است.',
    category: 'SETBACK',
    jurisdiction: 'طرح تفصیلی شهر تهران — محورهای اصلی',
    source: {
      document: 'طرح تفصیلی منطقه ۶ — برهای اصلاحی خیابان ولیعصر و بلوار کشاورز',
      version: 'ابلاغ ۱۳۹۶',
      issuer: 'شهرداری منطقه ۶ تهران — اداره کل طرح و برنامه',
      document_date: '۱۳۹۶/۰۵/۱۰',
      page: 42,
      clause: 'بند ۷.۴ — عقب‌نشینی معابر شریانی درجه ۲',
      effective_from: '۱۳۹۶/۰۶/۰۱',
      effective_to: null,
      source_uri: 'https://region6.tehran.ir/urban-regulations/setbacks-arterial-clause-7-4',
      evidence: 'نقشه خط پروژه‌های مصوب ساماندهی محور ولیعصر',
      verification_status: 'VERIFIED',
    },
    inputs: [
      {
        name: 'street_width',
        label: 'عرض گذر معبر مجاور',
        data_type: 'number',
        unit: 'm',
        required: true,
      },
      {
        name: 'provided_setback',
        label: 'عقب‌نشینی اعمال‌شده در طرح',
        data_type: 'number',
        unit: 'm',
        required: true,
      },
    ],
    applicability_ast: {
      type: 'greater_than_or_equal',
      data_type: 'boolean',
      children: [
        { type: 'input_reference', data_type: 'number', input_name: 'street_width' },
        { type: 'literal', data_type: 'number', value: 20 },
      ],
    },
    assertion_ast: {
      type: 'greater_than_or_equal',
      data_type: 'boolean',
      children: [
        { type: 'input_reference', data_type: 'number', input_name: 'provided_setback' },
        { type: 'literal', data_type: 'number', value: 3.5 },
      ],
    },
    human_readable: 'اگر عرض معبر ≥ ۲۰ متر باشد، عقب‌نشینی اعمال‌شده طرح ≥ ۳.۵ متر.',
    severity: 'BLOCKING',
    exceptions: [],
    precedences: [],
    test_cases: [
      {
        id: 'TC-SETB-01',
        name: 'عقب‌نشینی ۴ متر در گذر ۲۵ متری (منطبق)',
        test_type: 'HAPPY_PATH',
        inputs: { street_width: 25, provided_setback: 4 },
        expected_applicability: 'applicable',
        expected_outcome: 'pass',
      },
      {
        id: 'TC-SETB-02',
        name: 'عقب‌نشینی ۲ متر در گذر ۲۵ متری (نقض ضابطه عقب‌نشینی)',
        test_type: 'LOWER_BOUNDARY',
        inputs: { street_width: 25, provided_setback: 2 },
        expected_applicability: 'applicable',
        expected_outcome: 'fail',
      },
    ],
    test_runs: [],
    status: 'PUBLISHED',
    content_hash: '',
    source_hash: '',
    approval_hash: 'appr-hash-setb-01-v4',
    approved_by: 'دکتر محمدرضا سلطانی',
    approved_at: '۱۴۰۵/۰۲/۱۸',
    created_at: '۱۴۰۵/۰۲/۱۰',
    created_by: 'مهندس لیلا اکبری',
    effective_from: '۱۳۹۶/۰۶/۰۱',
    effective_to: null,
    is_synthetic: false,
  },

  // 6. RL-HEIGHT-01 v2 (PUBLISHED)
  {
    version_id: 'RL-HEIGHT-01-v2',
    rule_code: 'RL-HEIGHT-01',
    version_number: 2,
    title: 'سقف ارتفاع مجاز ابنیه در مجاورت خطوط انتقال نیرو و حریم مسیل',
    description: 'در مجاورت حریم خطوط کابل و انتقال نیرو، حداکثر ارتفاع مجاز ۱۸ متر و فاصله از حریم ایمنی حداقل ۱۵ متر می‌باشد.',
    category: 'HEIGHT',
    jurisdiction: 'حریم خطوط انتقال نیرو و آیین‌نامه ایمنی شهر تهران',
    source: {
      document: 'آیین‌نامه ایمنی حریم خطوط انتقال نیرو و بستر مسیل‌های شهری',
      version: 'مصوب هیئت وزیران — ۱۳۹۴',
      issuer: 'وزارت نیرو و شورای‌عالی شهرسازی',
      document_date: '۱۳۹۴/۰۳/۱۴',
      page: 12,
      clause: 'ماده ۸ — محدودیت‌های ارتفاعی در حریم کابل فشارقوی',
      effective_from: '۱۳۹۴/۰۴/۰۱',
      effective_to: null,
      source_uri: 'https://moe.gov.ir/regulations/power-lines-safety-clause-8',
      evidence: 'تصویب‌نامه شماره ۲۴۱۰۹/ت۵۰۱۸۴هـ هیئت وزیران',
      verification_status: 'VERIFIED',
    },
    inputs: [
      {
        name: 'distance_to_powerline',
        label: 'فاصله تا حریم کابل فشارقوی',
        data_type: 'number',
        unit: 'm',
        required: true,
      },
      {
        name: 'proposed_building_height',
        label: 'ارتفاع پیشنهادی ساختمان',
        data_type: 'number',
        unit: 'm',
        required: true,
      },
    ],
    applicability_ast: {
      type: 'less_than',
      data_type: 'boolean',
      children: [
        { type: 'input_reference', data_type: 'number', input_name: 'distance_to_powerline' },
        { type: 'literal', data_type: 'number', value: 30 },
      ],
    },
    assertion_ast: {
      type: 'less_than_or_equal',
      data_type: 'boolean',
      children: [
        { type: 'input_reference', data_type: 'number', input_name: 'proposed_building_height' },
        { type: 'literal', data_type: 'number', value: 18 },
      ],
    },
    human_readable: 'اگر فاصله از حریم کابل < ۳۰ متر باشد، ارتفاع ساختمان پیشنهادی ≤ ۱۸ متر.',
    severity: 'BLOCKING',
    exceptions: [],
    precedences: [],
    test_cases: [
      {
        id: 'TC-HGT-01',
        name: 'ارتفاع ۱۵ متر در فاصله ۲۵ متری (منطبق)',
        test_type: 'HAPPY_PATH',
        inputs: { distance_to_powerline: 25, proposed_building_height: 15 },
        expected_applicability: 'applicable',
        expected_outcome: 'pass',
      },
      {
        id: 'TC-HGT-02',
        name: 'ارتفاع ۲۲ متر در فاصله ۲۵ متری (نقض حریم)',
        test_type: 'UPPER_BOUNDARY',
        inputs: { distance_to_powerline: 25, proposed_building_height: 22 },
        expected_applicability: 'applicable',
        expected_outcome: 'fail',
      },
    ],
    test_runs: [],
    status: 'PUBLISHED',
    content_hash: '',
    source_hash: '',
    approval_hash: 'appr-hash-hgt-01-v2',
    approved_by: 'دکتر محمدرضا سلطانی',
    approved_at: '۱۴۰۵/۰۳/۱۰',
    created_at: '۱۴۰۵/۰۱/۱۵',
    created_by: 'مهندس لیلا اکبری',
    effective_from: '۱۳۹۴/۰۴/۰۱',
    effective_to: null,
    is_synthetic: false,
  },
];

// Initialize hashes for seed versions
SEED_RULE_VERSIONS.forEach(v => {
  v.content_hash = computeRuleContentHash(v);
  v.source_hash = computeSourceHash(v.source);
});

/* ============================================================
   SEED RULE PACKS & VERSIONS (Immutable Pack Architecture)
   ============================================================ */

export const SEED_RULE_PACKS: RulePack[] = [
  {
    id: 'PACK-TEH-2026',
    code: 'PACK-TEH-2026',
    title: 'بسته جامع ضوابط طرح تفصیلی شهر تهران (منطقه ۶)',
    description: 'بسته یکپارچه و نسخه‌دار ضوابط ملاک‌عمل طرح تفصیلی منطقه ۶ مشتمل بر تراکم، سطح اشغال، تعداد طبقات، حریم عقب‌نشینی و پارکینگ.',
    jurisdiction: 'شهرداری منطقه ۶ تهران',
    current_published_version: 4,
    latest_version: 4,
    owner: 'مهندس لیلا اکبری (متولی قواعد و ضوابط)',
    dependent_study_ids: ['ST-1405-014', 'ST-1405-021'],
    created_at: '۱۴۰۴/۰۸/۱۰',
    updated_at: '۱۴۰۵/۰۲/۱۸',
  },
];

export const SEED_RULE_PACK_VERSIONS: RulePackVersion[] = [
  // Historical Version 3 for Study Reproducibility
  {
    pack_version_id: 'PACK-TEH-2026-v3',
    pack_id: 'PACK-TEH-2026',
    version_number: 3,
    version_tag: 'PACK-TEH-2026-v3',
    title: 'بسته ضوابط طرح تفصیلی منطقه ۶ — نسخه ۳ (تاریخی)',
    jurisdiction: 'شهرداری منطقه ۶ تهران',
    rules: [
      {
        rule_code: 'RL-DENSITY-01',
        version_number: 3,
        version_id: 'RL-DENSITY-01-v3',
        content_hash: 'hist-hash-dens-v3',
      },
      {
        rule_code: 'RL-COVERAGE-01',
        version_number: 3,
        version_id: 'RL-COVERAGE-01-v3',
        content_hash: 'hist-hash-cov-v3',
      },
      {
        rule_code: 'RL-PARKING-01',
        version_number: 3,
        version_id: 'RL-PARKING-01-v3',
        content_hash: 'hist-hash-park-v3',
      },
    ],
    status: 'SUPERSEDED',
    content_hash: 'pack-hash-teh-2026-v3',
    approved_by: 'دکتر محمدرضا سلطانی',
    approved_at: '۱۴۰۴/۱۱/۲۰',
    published_by: 'مهندس لیلا اکبری',
    published_at: '۱۴۰۴/۱۱/۲۵',
    effective_from: '۱۴۰۴/۱۲/۰۱',
    effective_to: '۱۴۰۵/۰۲/۱۷',
    notes: 'نسخه تاریخی مورد استفاده در مطالعات سال ۱۴۰۴',
  },

  // Active Published Version 4
  {
    pack_version_id: 'PACK-TEH-2026-v4',
    pack_id: 'PACK-TEH-2026',
    version_number: 4,
    version_tag: 'PACK-TEH-2026-v4',
    title: 'بسته ضوابط طرح تفصیلی منطقه ۶ — نسخه ۴ (ملاک‌عمل فعلی)',
    jurisdiction: 'شهرداری منطقه ۶ تهران',
    rules: [
      {
        rule_code: 'RL-DENSITY-01',
        version_number: 4,
        version_id: 'RL-DENSITY-01-v4',
        content_hash: SEED_RULE_VERSIONS[0].content_hash,
      },
      {
        rule_code: 'RL-COVERAGE-01',
        version_number: 4,
        version_id: 'RL-COVERAGE-01-v4',
        content_hash: SEED_RULE_VERSIONS[1].content_hash,
      },
      {
        rule_code: 'RL-STOREYS-01',
        version_number: 4,
        version_id: 'RL-STOREYS-01-v4',
        content_hash: SEED_RULE_VERSIONS[2].content_hash,
      },
      {
        rule_code: 'RL-PARKING-01',
        version_number: 4,
        version_id: 'RL-PARKING-01-v4',
        content_hash: SEED_RULE_VERSIONS[3].content_hash,
      },
      {
        rule_code: 'RL-SETBACK-01',
        version_number: 4,
        version_id: 'RL-SETBACK-01-v4',
        content_hash: SEED_RULE_VERSIONS[4].content_hash,
      },
    ],
    precedence_policy_id: 'PREC-POLICY-TEH-01',
    status: 'PUBLISHED',
    content_hash: 'pack-hash-teh-2026-v4',
    approved_by: 'دکتر محمدرضا سلطانی',
    approved_at: '۱۴۰۵/۰۲/۱۸',
    published_by: 'مهندس لیلا اکبری',
    published_at: '۱۴۰۵/۰۲/۱۸',
    effective_from: '۱۴۰۵/۰۲/۱۸',
    effective_to: null,
    notes: 'نسخه رسمی ملاک‌عمل ارزیابی انطباق طرح‌ها و سناریوهای منطقه ۶',
  },
];

/* ============================================================
   SEED PRECEDENCES (Legal Precedence Policies)
   ============================================================ */

export const SEED_RULE_PRECEDENCES: RulePrecedence[] = [
  {
    id: 'PREC-001',
    target_rule_code: 'RL-DENSITY-01',
    precedes_rule_code: 'RL-STOREYS-01',
    authority: 'شورای‌عالی شهرسازی و معماری ایران',
    source: 'بند ۱۲ مصوبه پیرامون تقدم احکام سقف تراکم طرح جامع بر تعداد طبقات تفصیلی',
    effective_from: '۱۳۹۲/۰۱/۰۱',
    effective_to: null,
    rationale: 'احکام سقف تراکم جمعیتی و ساختمانی مصوب فرادست بر سقف تعداد طبقات تقدم قانونی دارد.',
    status: 'APPROVED',
  },
];

/* ============================================================
   SEED RULE REQUESTS (From Study Cases & Analysts)
   ============================================================ */

export const SEED_RULE_REQUESTS: RuleRequest[] = [
  {
    id: 'REQ-RL-1405-001',
    study_case_id: 'SC-1405-014',
    study_title: 'مطالعه بازآفرینی و ساماندهی بافت میانی امیرآباد (منطقه ۶)',
    requirement_id: 'REQ-R5-PARK',
    rule_code: 'RL-PARKING-01',
    title: 'درخواست انطباق و استعلام نسخه رسمی ضابطه پارکینگ تجمیعی',
    reason: 'OUTDATED',
    effective_date: '۱۴۰۵/۰۲/۱۸',
    region: 'منطقه ۶ تهران',
    impact: 'بدون این ضابطه ماژول M05 ظرفیت ترافیکی و ارزیابی پارکینگ مسدود می‌ماند.',
    requested_by: 'مهندس زهرا کاظمی (تحلیلگر شهری)',
    assigned_to: 'مهندس لیلا اکبری (متولی قواعد و ضوابط)',
    priority: 'HIGH',
    status: 'FULFILLED',
    fulfilled_rule_version: 4,
    fulfilled_pack_id: 'PACK-TEH-2026-v4',
    created_at: '۱۴۰۵/۰۲/۱۵',
    updated_at: '۱۴۰۵/۰۲/۱۸',
    started_at: '۱۴۰۵/۰۲/۱۶',
    fulfilled_at: '۱۴۰۵/۰۲/۱۸',
    note: 'نسخه v4 ضابطه با استناد به مصوبه ۵۲۸ کمیسیون ماده پنج منتشر و به مطالعه متصل شد.',
  },
];

/* ============================================================
   SEED RULE REQUIREMENTS FOR STUDY CASES
   ============================================================ */

export const SEED_RULE_REQUIREMENTS: RuleRequirement[] = [
  {
    id: 'REQ-R1-DENS',
    study_case_id: 'SC-1405-014',
    rule_code: 'RL-DENSITY-01',
    name: 'سقف تراکم ساختمانی پهنه مرکزی',
    category: 'DENSITY',
    reason: 'الزام قانونی کنترل سقف بارگذاری جمعیتی و کالبدی در پهنه سکونت',
    module_code: 'M01',
    scope: 'کل محدوده پلاک‌های محله ۳ و ۴ امیرآباد',
    required: true,
    blocking: true,
    satisfied: true,
    status: 'SATISFIED',
    attached_rule_version: 4,
    attached_pack_id: 'PACK-TEH-2026-v4',
  },
  {
    id: 'REQ-R2-COV',
    study_case_id: 'SC-1405-014',
    rule_code: 'RL-COVERAGE-01',
    name: 'حداکثر سطح اشغال مجاز ابنیه',
    category: 'SITE_COVERAGE',
    reason: 'حفظ فضای باز شهری و ضوابط کنترل سایه‌اندازی',
    module_code: 'M01',
    scope: 'پلاک‌های مسکونی',
    required: true,
    blocking: true,
    satisfied: true,
    status: 'SATISFIED',
    attached_rule_version: 4,
    attached_pack_id: 'PACK-TEH-2026-v4',
  },
  {
    id: 'REQ-R3-STOR',
    study_case_id: 'SC-1405-014',
    rule_code: 'RL-STOREYS-01',
    name: 'حداکثر تعداد طبقات مجاز',
    category: 'STOREYS',
    reason: 'کنترل خط آسمان و تناسب معابر با طبقات',
    module_code: 'M01',
    scope: 'پلاک‌های مسکونی عام',
    required: true,
    blocking: true,
    satisfied: true,
    status: 'SATISFIED',
    attached_rule_version: 4,
    attached_pack_id: 'PACK-TEH-2026-v4',
  },
  {
    id: 'REQ-R4-PARK',
    study_case_id: 'SC-1405-014',
    rule_code: 'RL-PARKING-01',
    name: 'الزام تأمین پارکینگ بر حسب کاربری',
    category: 'PARKING',
    reason: 'جلوگیری از کسری پارکینگ و ترافیک سرریز معابر فرعی',
    module_code: 'M05',
    scope: 'کل پلاک‌ها و واحدهای نوساز',
    required: true,
    blocking: true,
    satisfied: true,
    status: 'SATISFIED',
    attached_rule_version: 4,
    attached_pack_id: 'PACK-TEH-2026-v4',
  },
  {
    id: 'REQ-R5-SETB',
    study_case_id: 'SC-1405-014',
    rule_code: 'RL-SETBACK-01',
    name: 'حریم و عقب‌نشینی معابر شریانی',
    category: 'SETBACK',
    reason: 'رعایت بر اصلاحی خیابان‌های کارگر و کردستان',
    module_code: 'M01',
    scope: 'محورهای اصلی',
    required: true,
    blocking: true,
    satisfied: true,
    status: 'SATISFIED',
    attached_rule_version: 4,
    attached_pack_id: 'PACK-TEH-2026-v4',
  },
];

/* ============================================================
   SEED AUDIT LOGS
   ============================================================ */

export const SEED_RULE_AUDITS: RuleAudit[] = [
  {
    id: 'AUD-RL-001',
    actor: 'مهندس لیلا اکبری',
    role: 'ruleman',
    timestamp: '۱۴۰۵/۰۲/۱۰ ۱۰:۳۰',
    action: 'RULE_CREATED',
    entity: 'RULE',
    entity_id: 'RL-DENSITY-01',
    reason: 'ثبت ضابطه جدید سقف تراکم پهنه R122',
    content_hash: SEED_RULE_VERSIONS[0].content_hash,
  },
  {
    id: 'AUD-RL-002',
    actor: 'مهندس لیلا اکبری',
    role: 'ruleman',
    timestamp: '۱۴۰۵/۰۲/۱۰ ۱۱:۱۵',
    action: 'RULE_SOURCE_ADDED',
    entity: 'RULE_VERSION',
    entity_id: 'RL-DENSITY-01-v4',
    reason: 'افزودن استناد قانونی به بند ۴.۲ ضوابط طرح تفصیلی یکپارچه تهران',
  },
  {
    id: 'AUD-RL-003',
    actor: 'مهندس لیلا اکبری',
    role: 'ruleman',
    timestamp: '۱۴۰۵/۰۲/۱۵ ۱۴:۲۰',
    action: 'RULE_TESTED',
    entity: 'RULE_VERSION',
    entity_id: 'RL-DENSITY-01-v4',
    reason: 'اجرای ۵ آزمون مرزی و شمول (پاس شدن ۱۰۰٪ آزمون‌ها)',
  },
  {
    id: 'AUD-RL-004',
    actor: 'دکتر محمدرضا سلطانی',
    role: 'approver',
    timestamp: '۱۴۰۵/۰۲/۱۸ ۰۹:۴۰',
    action: 'RULE_APPROVED',
    entity: 'RULE_VERSION',
    entity_id: 'RL-DENSITY-01-v4',
    reason: 'تأیید تخصصی انطباق حقوقی و صحت درخت AST',
    content_hash: SEED_RULE_VERSIONS[0].content_hash,
  },
  {
    id: 'AUD-RL-005',
    actor: 'مهندس لیلا اکبری',
    role: 'ruleman',
    timestamp: '۱۴۰۵/۰۲/۱۸ ۱۱:۰۰',
    action: 'RULE_PACK_PUBLISHED',
    entity: 'RULE_PACK_VERSION',
    entity_id: 'PACK-TEH-2026-v4',
    reason: 'انتشار رسمی بسته ضوابط منطقه ۶ نسخه ۴ و قفل تغییرناپذیری',
  },
];
